### index
GET http://localhost:5169/


### get all games
GET http://localhost:5169/games


### get a game by id
GET http://localhost:5169/games/de07b456-71c4-4d17-b5b5-9373468cdbfe


### create a new game
POST http://localhost:5169/games
Content-Type: application/json

{
  "name": "Helldivers 2",
  "genreId": "48743F7C-B826-45A4-B7C2-240EFBF0CB09",
  "price": 59.99,
  "releaseDate": "2024-07-13",
  "description": "save the galaxy from alien threats!!"
}

###
PUT http://localhost:5169/games/8ebd002e-0db5-4c7c-afef-f084db766bf8
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genreId": "1EE90AA6-0FB2-4799-87C6-84A0C35D2510",
  "price": 89.99,
  "releaseDate": "2025-02-22",
  "description": "updated description!!!"
}

###
DELETE http://localhost:5169/games/f839d5dc-8b58-4429-b125-91e7e4e2d75b
Content-Type: application/json

